---
- name: Copy host certificates to grid-security
  copy:
    src: "/etc/grid-security/host{{ item }}.pem"
    dest: "/etc/grid-security/condor{{ item }}.pem"
    remote_src: true
    owner: condor
    group: condor
  loop:
    - cert
    - key

- name: Configure HTCondor CE
  template:
    src: "{{ item.src }}"
    dest: "/etc/condor-ce/{{ item.dest }}"
  loop:
    - src: ce-site-security.conf.j2
      dest: config.d/59-site-security.conf
    - src: configured-attributes.conf.j2
      dest: config.d/60-configured-attributes.conf
    - src: job-routes.conf.j2
      dest: config.d/61-job-routes.conf
  notify: reconfigure htcondor_ce

- name: Configure BDII for HTCondor-CE provider
  block:
    - name: Install and configure htcondor-ce-bdii
      package:
        name: htcondor-ce-bdii
        state: installed
    - template:
        src: ce-bdii.conf.j2
        dest: "/etc/condor/config.d/99-ce-bdii.conf"
      when: htcondor_ce_enable_bdii 
      notify: reconfigure htcondor_ce


- name: Enable Scitoken Auth
  block:
    - name: Uncomment AUTH_SSL syntax to enable SCITOKENS
      replace:
        path: /etc/condor-ce/config.d/01-ce-auth.conf
        regexp: '# AUTH_SSL_'
        replace: 'AUTH_SSL_'
    - name: Add scitoken id for VOs
      template:
        src: scitokens.conf.j2
        dest: /etc/condor-ce/mapfiles.d/10-scitokens.conf
      notify: reconfigure htcondor_ce

- name: Enable SSL Auth.
  block:
    - name: Create ssl-auth.conf for SSL auth
      template:
        src: ssl-auth.conf.j2
        dest: /etc/condor-ce/config.d/90-ssl-auth.conf
    - name: Add SSL mapping for X509 DN
      template:
        src: ssl.conf.j2
        dest: /etc/condor-ce/mapfiles.d/15-ssl.conf
      notify: reconfigure htcondor_ce

- name: Change LRMS Collector location if htcondor_ce_lrm_collector_is_set
  lineinfile:
    path: /etc/condor-ce/config.d/02-ce-condor.conf
    regexp: "JOB_ROUTER_SCHEDD2_POOL=*"
    line: "JOB_ROUTER_SCHEDD2_POOL={{ htcondor_ce_lrms_collector }}:9618"
  when:
    - htcondor_ce_lrms_collector is defined
    - htcondor_ce_batch_system == "condor"
  notify: reconfigure htcondor_ce

- name: Start HTCondor CE
  service:
    name: condor-ce
    state: started
    enabled: true
  register: service_condor_ce
