---
- name: "Install HTCondor-CE packages for {{ htcondor_ce_batch_system }}"
  package:
    name:
      - htcondor-ce-client
      - htcondor-ce-apel
      - htcondor-ce-view
      - htcondor-ce
      - "htcondor-ce-{{ htcondor_ce_batch_system }}"
