---
- name: "Install HTCondor-CE packages for {{ htcondor_ce_batch_system }}"
  package:
    name:
      - htcondor-ce-client
      - htcondor-ce-view
      - htcondor-ce
      - "htcondor-ce-{{ htcondor_ce_batch_system }}"
- name: "Install HTCondor-CE packages for apel"
  package:
    name: htcondor-ce-apel
    state: present
  when: htcondor_ce_enable_apel 
