---
- name: Install HTCondor repository
  yum:
    name: "https://research.cs.wisc.edu/htcondor/repo/{{ condor_version }}/htcondor-release-current.el{{ ansible_distribution_major_version }}.noarch.rpm"
    disable_gpg_check: yes
  when: ansible_facts['distribution_file_variety'] == "RedHat"
- name: Enable powertools repo for CentOS8 variation.
  shell:
    cmd: dnf config-manager --set-enabled powertools
  when:
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"
- name: Enable crb repo for EL9 variation.
  shell:
    cmd: dnf config-manager --set-enabled crb
  when:
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "9"
